name: nces
channels:
  - pytorch
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex
  - backcall
  - blas
  - bzip2
  - ca-certificates
  - certifi
  - cudatoolkit
  - cycler
  - dbus
  - decorator
  - expat
  - ffmpeg
  - fontconfig
  - freetype
  - glib
  - gmp
  - gnutls
  - gst-plugins-base
  - gstreamer
  - icu
  - intel-openmp
  - ipykernel
  - ipython
  - ipython_genutils
  - jedi
  - joblib
  - jpeg
  - kiwisolver
  - lame
  - lcms2
  - ld_impl_linux-64
  - libffi
  - libgcc-ng
  - libgfortran-ng
  - libiconv
  - libpng
  - libsodium
  - libstdcxx-ng
  - libtiff
  - libuuid
  - libuv
  - libxcb
  - libxml2
  - lz4-c
  - matplotlib
  - matplotlib-base
  - mkl
  - mkl-service
  - mkl_fft
  - mkl_random
  - ncurses
  - nettle
  - ninja
  - numpy
  - numpy-base
  - olefile
  - openh264
  - openssl
  - pandas
  - parso
  - pcre
  - pexpect
  - pickleshare
  - pillow
  - pip
  - prompt-toolkit
  - ptyprocess
  - pygments
  - pyparsing
  - pyqt
  - python
  - python_abi
  - pytorch
  - pytz
  - qt
  - readline
  - scikit-learn
  - scipy
  - setuptools
  - sip
  - six
  - sortedcontainers
  - sqlite
  - threadpoolctl
  - tk
  - torchaudio
  - torchvision
  - tornado
  - typing_extensions
  - tzdata
  - wcwidth
  - wheel
  - xz
  - zeromq
  - zlib
  - zstd
  - pip:
    - aiohttp
    - aiosignal
    - argon2-cffi
    - argon2-cffi-bindings
    - async-timeout
    - attrs
    - beautifulsoup4
    - bleach
    - cffi
    - chardet
    - charset-normalizer
    - datasets
    - defusedxml
    - dill
    - docutils
    - entrypoints
    - fastjsonschema
    - filelock
    - frozenlist
    - fsspec
    - gdown
    - gensim
    - huggingface-hub
    - idna
    - iniconfig
    - ipdb
    - ipywidgets
    - isodate
    - jinja2
    - jsonschema
    - jupyter-client
    - jupyter-core
    - jupyterlab-pygments
    - jupyterlab-widgets
    - kivy-garden
    - markupsafe
    - mistune
    - multidict
    - multiprocess
    - nbclient
    - nbconvert
    - nbformat
    - nest-asyncio
    - notebook
    - owlready2
    - packaging
    - pandocfilters
    - pluggy
    - prometheus-client
    - py
    - pyarrow
    - pycparser
    - pyrsistent
    - pysocks
    - pytest
    - python-dateutil
    - python-slugify
    - pyyaml
    - pyzmq
    - rdflib
    - regex
    - requests
    - responses
    - send2trash
    - sentencepiece
    - smart-open
    - soupsieve
    - terminado
    - text-unidecode
    - tinycss2
    - tokenizers
    - toml
    - tqdm
    - traitlets
    - transformers
    - urllib3
    - webencodings
    - widgetsnbextension
    - xxhash
    - yarl
